version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
      - rabbitmq
      - postgres

  redis:
    image: "redis:6.2"

  postgres:
    image: "postgres:16"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: -p ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.celery_tasks:celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
      - postgres

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.celery_tasks:celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
      - postgres

volumes:
  postgres_data:
